### ISSUE TITLE
Error: fakeredis: You've closed this connection with QUIT, cannot INCR

### ISSUE THREAD

**Issue by rcbop** [guilleiguaran/fakeredis#167]
I'm running mocha tests on a node REST API that is using fakeredis for tests.

This is running inside a docker container with nodejs

When I try running I get the following error:

/node_modules/fakeredis/lib/connection.js:244
    throw new Error("fakeredis: You've closed this connection with QUIT, cannot " + entry.command);
    ^

Error: fakeredis: You've closed this connection with QUIT, cannot INCR
    at CLOSED (/home/jenkins/workspace/Rufus_Test_DEV/node_modules/fakeredis/lib/connection.js:244:11)
    at push (/home/jenkins/workspace/Rufus_Test_DEV/node_modules/fakeredis/lib/connection.js:16:5)
    at RedisClient.cl.send_command (/home/jenkins/workspace/Rufus_Test_DEV/node_modules/fakeredis/main.js:133:7)
    at RedisClient.(anonymous function) (/home/jenkins/workspace/Rufus_Test_DEV/node_modules/fakeredis/node_modules/redis/index.js:896:21)
    at worker.fail (/home/jenkins/workspace/Rufus_Test_DEV/node_modules/node-resque/lib/worker.js:215:25)
    at worker.completeJob (/home/jenkins/workspace/Rufus_Test_DEV/node_modules/node-resque/lib/worker.js:191:10)
    at Domain.<anonymous> (/home/jenkins/workspace/Rufus_Test_DEV/node_modules/node-resque/lib/worker.js:133:10)
    at emitOne (events.js:77:13)
    at Domain.emit (events.js:169:7)
    at emitError (domain.js:66:24)
    at Domain.errorHandler [as _errorHandler] (domain.js:110:18)
    at process._fatalException (node.js:221:33)
    at Domain.errorHandler [as _errorHandler] (domain.js:137:26)
    at process._fatalException (node.js:221:33)
    at Domain.errorHandler [as _errorHandler] (domain.js:137:26)
    at process._fatalException (node.js:221:33)
    at Domain.errorHandler [as _errorHandler] (domain.js:137:26)
    at process._fatalException (node.js:221:33)

**Comment by guilleiguaran** [comment]
wrong project, I think you are talking about https://github.com/hdachev/fakeredis
