### ISSUE TITLE
LoadError: cannot load such file -- rspec/core

### ISSUE THREAD

**Issue by vcardillo** [guilleiguaran/fakeredis#176]
The file causing the problem is located in
`lib/fakeredis/rspec.rb`

If it's important, this file is located here on my system:
`~/.gem/ruby/2.3.1/bundler/gems/fakeredis-0136520e4b20/lib/fakeredis/rspec.rb`

Notice that's apparently a gem installed under the bundler folder.

Problem:
```
require 'rspec/core'
require 'fakeredis'
```

The `require 'rspec/core'` line seems to be causing this error:

> LoadError: cannot load such file -- rspec/core

Full stack trace:

```
01:09:54 worker.1 | LoadError: cannot load such file -- rspec/core
01:09:54 worker.1 | /home/vincent/.gem/ruby/2.3.1/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
01:09:54 worker.1 | /home/vincent/.gem/ruby/2.3.1/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
01:09:54 worker.1 | /home/vincent/.gem/ruby/2.3.1/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
01:09:54 worker.1 | /home/vincent/.gem/ruby/2.3.1/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
01:09:54 worker.1 | /home/vincent/.gem/ruby/2.3.1/bundler/gems/fakeredis-0136520e4b20/lib/fakeredis/rspec.rb:14:in `<top (required)>'
01:09:54 worker.1 | /home/vincent/.gem/ruby/2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:91:in `require'
01:09:54 worker.1 | /home/vincent/.gem/ruby/2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
01:09:54 worker.1 | /home/vincent/.gem/ruby/2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `each'
01:09:54 worker.1 | /home/vincent/.gem/ruby/2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `block in require'
01:09:54 worker.1 | /home/vincent/.gem/ruby/2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `each'
01:09:54 worker.1 | /home/vincent/.gem/ruby/2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `require'
01:09:54 worker.1 | /home/vincent/.gem/ruby/2.3.1/gems/bundler-1.13.6/lib/bundler.rb:106:in `require'
01:09:54 worker.1 | /var/www/onemed/onelife/config/application.rb:9:in `<top (required)>'
01:09:54 worker.1 | /var/www/onemed/onelife/Rakefile:4:in `<top (required)>'
01:09:54 worker.1 | /home/vincent/.gem/ruby/2.3.1/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
01:09:54 worker.1 | /home/vincent/.gem/ruby/2.3.1/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'
01:09:54 worker.1 | /home/vincent/.gem/ruby/2.3.1/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
01:09:54 worker.1 | /home/vincent/.gem/ruby/2.3.1/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
01:09:54 worker.1 | /home/vincent/.gem/ruby/2.3.1/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
01:09:54 worker.1 | /home/vincent/.gem/ruby/2.3.1/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
01:09:54 worker.1 | /home/vincent/.gem/ruby/2.3.1/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
01:09:54 worker.1 | /home/vincent/.gem/ruby/2.3.1/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
01:09:54 worker.1 | /home/vincent/.gem/ruby/2.3.1/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
01:09:54 worker.1 | /home/vincent/.gem/ruby/2.3.1/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
01:09:54 worker.1 | /home/vincent/.gem/ruby/2.3.1/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
01:09:54 worker.1 | /home/vincent/.gem/ruby/2.3.1/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
01:09:54 worker.1 | /home/vincent/.gem/ruby/2.3.1/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
01:09:54 worker.1 | /home/vincent/.gem/ruby/2.3.1/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
01:09:54 worker.1 | /home/vincent/.gem/ruby/2.3.1/bin/bundle:23:in `load'
01:09:54 worker.1 | /home/vincent/.gem/ruby/2.3.1/bin/bundle:23:in `<main>'
01:09:54 worker.1 | (See full trace by running task with --trace)
01:09:54 worker.1 | exited with code 1
01:09:54 system   | sending SIGTERM to all processes
01:09:54 web.1    | terminated by SIGTERM
```

**Comment by caius** [comment]
@vcardillo is this still an issue please?

**Comment by caius** [comment]
Presuming this isn't an issue & closing. If it still is, please reopen and we can take a look 😸
