### ISSUE TITLE
don't work in rails test environment

### ISSUE THREAD

**Issue by strangerxx** [guilleiguaran/fakeredis#202]
Run rspec file:
```ruby
require 'rails_helper'

RSpec.describe Fight, type: :model do

  describe "object" do
    before(:each) do
      first_user = 1
      second_user = 2
      @fight = Fight.new(first_user: first_user, second_user: second_user,
                         exercise_type: 0)
    end

    describe "validation" do
      it "first_user should be presence" do
        @fight.first_user = nil
        expect(@fight.valid?).to be false
      end

      it "second_user should be presence" do
        @fight.second_user = nil
        expect(@fight.valid?).to be false
      end

      it "exercise_type should be presence" do
        @fight.exercise_type = nil
        expect(@fight.valid?).to be false
      end

      it "should be valid" do
        expect(@fight).to be_valid
      end
    end

    it "after save object first_progress and second_progress not be nil" do
      @fight.save

      expect(@fight.id).to_not be nil

      expect(@fight.first_progress).to_not be nil
      expect(@fight.second_progress).to_not be nil
    end
  end

  describe "add_fight" do
    before(:all) do
      redis = Redis.new
      redis.set "foo", "bar"
    end

    before(:each) do
      @user_id = 1
    end

    it "test" do
      # Fight.add_fight(@user_id)
    end

    after(:each) do
    end
  end

  after(:each) do
    DatabaseCleaner.strategy = :truncation
    DatabaseCleaner.clean
  end
end
```
I get error:

     Failure/Error: redis.set "foo", "bar"
     Redis::CannotConnectError:
       Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)
     # /home/icestranger/.rvm/gems/ruby-2.4.0@game/gems/redis-4.0.1/lib/redis/client.rb:344:in `rescue in establish_connection'
     # /home/icestranger/.rvm/gems/ruby-2.4.0@game/gems/redis-4.0.1/lib/redis/client.rb:329:in `establish_connection'
     # /home/icestranger/.rvm/gems/ruby-2.4.0@game/gems/redis-4.0.1/lib/redis/client.rb:99:in `block in connect'
     # /home/icestranger/.rvm/gems/ruby-2.4.0@game/gems/redis-4.0.1/lib/redis/client.rb:291:in `with_reconnect'
     # /home/icestranger/.rvm/gems/ruby-2.4.0@game/gems/redis-4.0.1/lib/redis/client.rb:98:in `connect'
     # /home/icestranger/.rvm/gems/ruby-2.4.0@game/gems/redis-4.0.1/lib/redis/client.rb:363:in `ensure_connected'
     # /home/icestranger/.rvm/gems/ruby-2.4.0@game/gems/redis-4.0.1/lib/redis/client.rb:219:in `block in process'
     # /home/icestranger/.rvm/gems/ruby-2.4.0@game/gems/redis-4.0.1/lib/redis/client.rb:304:in `logging'
     # /home/icestranger/.rvm/gems/ruby-2.4.0@game/gems/redis-4.0.1/lib/redis/client.rb:218:in `process'
     # /home/icestranger/.rvm/gems/ruby-2.4.0@game/gems/redis-4.0.1/lib/redis/client.rb:118:in `call'
     # /home/icestranger/.rvm/gems/ruby-2.4.0@game/gems/redis-4.0.1/lib/redis.rb:783:in `block in set'
     # /home/icestranger/.rvm/gems/ruby-2.4.0@game/gems/redis-4.0.1/lib/redis.rb:45:in `block in synchronize'
     # /home/icestranger/.rvm/gems/ruby-2.4.0@game/gems/redis-4.0.1/lib/redis.rb:45:in `synchronize'
     # /home/icestranger/.rvm/gems/ruby-2.4.0@game/gems/redis-4.0.1/lib/redis.rb:779:in `set'
     # ./spec/models/fight_spec.rb:47:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Errno::ECONNREFUSED:
     #   Connection refused
     #   /home/icestranger/.rvm/gems/ruby-2.4.0@game/gems/redis-4.0.1/lib/redis/connection/hiredis.rb:19:in `connect'

I check in console and get result:
```
ruby-2.4.0@game [icestranger@arch_notebook_jul game]$ rails c
Running via Spring preloader in process 24606
Loading development environment (Rails 5.1.4)
2.4.0 :001 > require "fakeredis"
 => true 
2.4.0 :002 > redis = Redis.new
 => #<Redis client v4.0.1 for redis://127.0.0.1:6379/0> 
2.4.0 :003 > redis.set "foo", "bar"
 => "OK" 
2.4.0 :004 > exit
ruby-2.4.0@game [icestranger@arch_notebook_jul game]$ rails c test
Running via Spring preloader in process 25160
Loading test environment (Rails 5.1.4)
irb: warn: can't alias context from irb_context.
2.4.0 :001 > require "fakeredis"
 => false 
2.4.0 :002 > redis = Redis.new
 => #<Redis client v4.0.1 for redis://127.0.0.1:6379/0> 
2.4.0 :003 > redis.set "foo", "bar"
Redis::CannotConnectError: Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)
	from (irb):3
```
My Gemfile:
```ruby
source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails'
# Use Puma as the app server
gem 'puma'
# Use SCSS for stylesheets
gem 'sass-rails'
gem 'bootstrap-sass'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier'
gem 'slim'
gem 'slim-rails'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

#font for new design rails
gem "font-awesome-rails"
#normalize for css
gem 'normalize-rails'

# user auth
gem 'devise'

gem 'redis'
gem 'hiredis' # optional

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Use sqlite3 as the database for Active Record
  gem 'sqlite3'
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'cucumber-rails', :require => false
  # database_cleaner is not required, but highly recommended
  gem 'database_cleaner'
  gem "factory_bot_rails"

  # Automagically launches tests for changed files
  gem 'guard'
  # And updates gems when needed
  gem 'guard-bundler', require: false
  # And auto starts rails server
  gem 'guard-rails'
  gem 'guard-spring'
  gem 'guard-migrate'
  gem 'guard-cucumber'
  gem 'guard-rspec', require: false

end

group :test do
  gem "rspec"
  gem 'rspec-rails'
  gem "fakeredis", require: "fakeredis/rspec", git: 'https://github.com/guilleiguaran/fakeredis'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console'
  gem 'listen'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen'

  # Use Capistrano for deployment
  gem 'capistrano-rails'
  gem 'capistrano-rvm'
end

group :production do
  gem 'pg'
  gem 'unicorn'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```
P.S. This my first issue and my english is bad.

**Comment by strangerxx** [comment]
I'm solve problem. don't use "Redis.new" before include fakeredis.
