### ISSUE TITLE
tests are failing with redis 4.1.x - ArgumentError: invalid value for Float(): "Infinity"

### ISSUE THREAD

**Issue by pravi** [guilleiguaran/fakeredis#239]
Test log below
bundle install --path vendor/bundle
bundle exec rake

```
Failures:

  1) KeysMethods with extended options uses nx option to only set the key if it does not already exist
     Failure/Error: expect(@client.set("key1", "2", { :nx => true })).to eq(false)
     
       expected: false
            got: 0
     
       (compared using ==)
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-support-3.9.2/lib/rspec/support.rb:97:in `block in <module:Support>'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-support-3.9.2/lib/rspec/support.rb:106:in `notify_failure'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-expectations-3.9.0/lib/rspec/expectations/fail_with.rb:35:in `fail_with'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-expectations-3.9.0/lib/rspec/expectations/handler.rb:38:in `handle_failure'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-expectations-3.9.0/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-expectations-3.9.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-expectations-3.9.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-expectations-3.9.0/lib/rspec/expectations/expectation_target.rb:65:in `to'
     # ./spec/keys_spec.rb:377:in `block (3 levels) in <module:FakeRedis>'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:257:in `instance_exec'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:257:in `block in run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:503:in `block in with_around_and_singleton_context_hooks'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:460:in `block in with_around_example_hooks'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:472:in `block in run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:610:in `run_around_example_hooks_for'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:472:in `run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:460:in `with_around_example_hooks'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:503:in `with_around_and_singleton_context_hooks'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:254:in `run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:633:in `block in run_examples'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:629:in `map'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:629:in `run_examples'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:595:in `run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:596:in `block in run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:596:in `map'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:596:in `run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:121:in `map'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/configuration.rb:2031:in `with_suite_hooks'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/reporter.rb:74:in `report'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:115:in `run_specs'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:89:in `run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:71:in `run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:45:in `invoke'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/exe/rspec:4:in `<main>'

  2) KeysMethods with extended options uses xx option to only set the key if it already exists
     Failure/Error: expect(@client.set("key2", "1", { :xx => true })).to eq(false)
     
       expected: false
            got: 0
     
       (compared using ==)
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-support-3.9.2/lib/rspec/support.rb:97:in `block in <module:Support>'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-support-3.9.2/lib/rspec/support.rb:106:in `notify_failure'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-expectations-3.9.0/lib/rspec/expectations/fail_with.rb:35:in `fail_with'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-expectations-3.9.0/lib/rspec/expectations/handler.rb:38:in `handle_failure'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-expectations-3.9.0/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-expectations-3.9.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-expectations-3.9.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-expectations-3.9.0/lib/rspec/expectations/expectation_target.rb:65:in `to'
     # ./spec/keys_spec.rb:383:in `block (3 levels) in <module:FakeRedis>'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:257:in `instance_exec'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:257:in `block in run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:503:in `block in with_around_and_singleton_context_hooks'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:460:in `block in with_around_example_hooks'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:472:in `block in run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:610:in `run_around_example_hooks_for'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:472:in `run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:460:in `with_around_example_hooks'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:503:in `with_around_and_singleton_context_hooks'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:254:in `run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:633:in `block in run_examples'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:629:in `map'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:629:in `run_examples'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:595:in `run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:596:in `block in run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:596:in `map'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:596:in `run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:121:in `map'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/configuration.rb:2031:in `with_suite_hooks'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/reporter.rb:74:in `report'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:115:in `run_specs'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:89:in `run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:71:in `run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:45:in `invoke'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/exe/rspec:4:in `<main>'

  3) KeysMethods with extended options does not set the key if both xx and nx option are specified
     Failure/Error: expect(@client.set("key2", "1", { :nx => true, :xx => true })).to eq(false)
     
       expected: false
            got: 0
     
       (compared using ==)
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-support-3.9.2/lib/rspec/support.rb:97:in `block in <module:Support>'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-support-3.9.2/lib/rspec/support.rb:106:in `notify_failure'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-expectations-3.9.0/lib/rspec/expectations/fail_with.rb:35:in `fail_with'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-expectations-3.9.0/lib/rspec/expectations/handler.rb:38:in `handle_failure'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-expectations-3.9.0/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-expectations-3.9.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-expectations-3.9.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-expectations-3.9.0/lib/rspec/expectations/expectation_target.rb:65:in `to'
     # ./spec/keys_spec.rb:391:in `block (3 levels) in <module:FakeRedis>'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:257:in `instance_exec'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:257:in `block in run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:503:in `block in with_around_and_singleton_context_hooks'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:460:in `block in with_around_example_hooks'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:472:in `block in run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:610:in `run_around_example_hooks_for'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:472:in `run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:460:in `with_around_example_hooks'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:503:in `with_around_and_singleton_context_hooks'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:254:in `run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:633:in `block in run_examples'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:629:in `map'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:629:in `run_examples'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:595:in `run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:596:in `block in run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:596:in `map'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:596:in `run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:121:in `map'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/configuration.rb:2031:in `with_suite_hooks'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/reporter.rb:74:in `report'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:115:in `run_specs'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:89:in `run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:71:in `run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:45:in `invoke'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/exe/rspec:4:in `<main>'

  4) SortedSetsMethods should add a member to a sorted set, or update its score if it already exists
     Failure/Error: expect(@client.zscore("key2", "val")).to eq(Infinity)
     
     ArgumentError:
       invalid value for Float(): "Infinity"
     # ./vendor/bundle/ruby/2.5.0/gems/redis-4.1.3/lib/redis.rb:3357:in `Float'
     # ./vendor/bundle/ruby/2.5.0/gems/redis-4.1.3/lib/redis.rb:3357:in `block in <class:Redis>'
     # ./vendor/bundle/ruby/2.5.0/gems/redis-4.1.3/lib/redis/client.rb:129:in `call'
     # ./vendor/bundle/ruby/2.5.0/gems/redis-4.1.3/lib/redis.rb:1732:in `block in zscore'
     # ./vendor/bundle/ruby/2.5.0/gems/redis-4.1.3/lib/redis.rb:52:in `block in synchronize'
     # /usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
     # ./vendor/bundle/ruby/2.5.0/gems/redis-4.1.3/lib/redis.rb:52:in `synchronize'
     # ./vendor/bundle/ruby/2.5.0/gems/redis-4.1.3/lib/redis.rb:1731:in `zscore'
     # ./spec/sorted_sets_spec.rb:20:in `block (2 levels) in <module:FakeRedis>'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:257:in `instance_exec'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:257:in `block in run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:503:in `block in with_around_and_singleton_context_hooks'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:460:in `block in with_around_example_hooks'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:472:in `block in run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:610:in `run_around_example_hooks_for'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:472:in `run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:460:in `with_around_example_hooks'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:503:in `with_around_and_singleton_context_hooks'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:254:in `run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:633:in `block in run_examples'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:629:in `map'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:629:in `run_examples'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:595:in `run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:121:in `map'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/configuration.rb:2031:in `with_suite_hooks'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/reporter.rb:74:in `report'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:115:in `run_specs'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:89:in `run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:71:in `run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:45:in `invoke'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/exe/rspec:4:in `<main>'

  5) SortedSetsMethods should handle infinity values when incrementing a sorted set key
     Failure/Error: expect(@client.zincrby("bar", "+inf", "s2")).to eq(Infinity)
     
     ArgumentError:
       invalid value for Float(): "Infinity"
     # ./vendor/bundle/ruby/2.5.0/gems/redis-4.1.3/lib/redis.rb:3357:in `Float'
     # ./vendor/bundle/ruby/2.5.0/gems/redis-4.1.3/lib/redis.rb:3357:in `block in <class:Redis>'
     # ./vendor/bundle/ruby/2.5.0/gems/redis-4.1.3/lib/redis/client.rb:129:in `call'
     # ./vendor/bundle/ruby/2.5.0/gems/redis-4.1.3/lib/redis.rb:1602:in `block in zincrby'
     # ./vendor/bundle/ruby/2.5.0/gems/redis-4.1.3/lib/redis.rb:52:in `block in synchronize'
     # /usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
     # ./vendor/bundle/ruby/2.5.0/gems/redis-4.1.3/lib/redis.rb:52:in `synchronize'
     # ./vendor/bundle/ruby/2.5.0/gems/redis-4.1.3/lib/redis.rb:1601:in `zincrby'
     # ./spec/sorted_sets_spec.rb:139:in `block (2 levels) in <module:FakeRedis>'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:257:in `instance_exec'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:257:in `block in run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:503:in `block in with_around_and_singleton_context_hooks'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:460:in `block in with_around_example_hooks'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:472:in `block in run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:610:in `run_around_example_hooks_for'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:472:in `run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:460:in `with_around_example_hooks'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:503:in `with_around_and_singleton_context_hooks'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:254:in `run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:633:in `block in run_examples'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:629:in `map'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:629:in `run_examples'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:595:in `run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:121:in `map'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/configuration.rb:2031:in `with_suite_hooks'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/reporter.rb:74:in `report'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:115:in `run_specs'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:89:in `run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:71:in `run'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:45:in `invoke'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/exe/rspec:4:in `<main>'

Finished in 0.42867 seconds (files took 0.43477 seconds to load)
399 examples, 5 failures, 1 pending

Failed examples:

rspec ./spec/keys_spec.rb:375 # KeysMethods with extended options uses nx option to only set the key if it does not already exist
rspec ./spec/keys_spec.rb:382 # KeysMethods with extended options uses xx option to only set the key if it already exists
rspec ./spec/keys_spec.rb:390 # KeysMethods with extended options does not set the key if both xx and nx option are specified
rspec ./spec/sorted_sets_spec.rb:11 # SortedSetsMethods should add a member to a sorted set, or update its score if it already exists
rspec ./spec/sorted_sets_spec.rb:138 # SortedSetsMethods should handle infinity values when incrementing a sorted set key
```

**Comment by guilleiguaran** [comment]
Can you test with 0.8.0?

**Comment by pravi** [comment]
@guilleiguaran thanks for 0.8.0, I can confirm the new version is working.
